/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {AddTool, DivideTool, DoneForNow, MultiplyTool, SubtractTool} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  DetermineNextStep(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): AddTool | SubtractTool | MultiplyTool | DivideTool | DoneForNow {
    try {
      return this.runtime.parseLlmResponse(
        "DetermineNextStep",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as AddTool | SubtractTool | MultiplyTool | DivideTool | DoneForNow
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  DetermineNextStep(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (((partial_types.AddTool | null) | (partial_types.SubtractTool | null) | (partial_types.MultiplyTool | null) | (partial_types.DivideTool | null) | null) | (partial_types.DoneForNow | null)) {
    try {
      return this.runtime.parseLlmResponse(
        "DetermineNextStep",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (((partial_types.AddTool | null) | (partial_types.SubtractTool | null) | (partial_types.MultiplyTool | null) | (partial_types.DivideTool | null) | null) | (partial_types.DoneForNow | null))
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}